# Simple workflow for deploying static content to GitHub Pages
name: Deploy static Docs to Pages

on:
  # Runs on pushes changes the path
  push:
    paths: ["apps/docs/src/stories"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

#       - name: Setup Pages
#         uses: actions/configure-pages@v3
  
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: apps/docs/storybook-static
  
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v1

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: apps/docs/storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: apps/docs # The folder that we serve our Storybook files from
