name: Publish Packages

on:
  release:
    types: [published]

jobs:
  check-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Tests
        working-directory: packages/visu
        run: npm run test:coverage

      - name: Create .npmrc
        working-directory: packages/visu
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc

      - name: Publish
        working-directory: packages/visu
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
